### ISSUE TITLE
Custom Updater

### ISSUE THREAD

**Issue by h4nc** [rgruebel/ha_zigbee2mqtt_networkmap#1]
Could you consider adding this to the custom updater?

https://github.com/custom-components/custom_updater?files=1

**Comment by rgruebel** [comment]
Hi, I'm not using the custom updater myself at the moment. I will have a look at it anyway.

**Comment by h4nc** [comment]
Did you have a look ;-)

**Comment by rgruebel** [comment]
Not yet, sorry. Maybe next weekend I'll have some time to have a look at it.

**Comment by rgruebel** [comment]
I'm afraid at the moment it's not possible to update this component with the custom updater, because files have to be downloaded into the www folder as well. If I understood it correctly, this is not possible yet.

**Comment by h4nc** [comment]
If I remember @alanste had a similar issue. It was only possible to update one file. He opened an issue and the them around  custom updater fixed it pretty quick. 

Maybe they would also make it possible for your component.

**Comment by h4nc** [comment]
Let's close this. Custom Updater is deprecated. 

See https://github.com/rgruebel/ha_zigbee2mqtt_networkmap/issues/11
