### ISSUE TITLE
map does not show anymore the link of end_devices

### ISSUE THREAD

**Issue by papperone** [rgruebel/ha_zigbee2mqtt_networkmap#10]
Hi, the map generation was perfectly working but it's not anymore since yesterday; the only changes I did was to upgrade the CC2531 coordinator firmware and since the despite all sensors and CC2531 routers works as before the map generated shows only the connection between coordinator and router and with just one arrow (from router to coordinator) while before it was doble arrow; all sensor are "floating" in the map without anymore the arrows that was showing to which CC2531 they were connected to.
I saw as well that zigbee2mqtt is updated to version 1.4 but the addon is still 1.3.1, can it be that firmware was not the issue and it's realted to outdated addon?

**Comment by rgruebel** [comment]
This is a zigbee2mqtt bug. I already had the same problem. Unfortunately only a new pairing of the devices helped. 
[zigbee map - devices work but don't show as connected](https://github.com/Koenkk/zigbee2mqtt/issues/1001)

**Comment by papperone** [comment]
cannot be a bug as until last evening the map was perfectly working and I just updated the  firmware of the coordinator, as a proog I just paired again 2 of myu devices and they keep on showing on the map but not "graphically" connected to anyone...

**Comment by rgruebel** [comment]
In my case it also occurred after a firmware update.

**Comment by papperone** [comment]
ok clear, I just did it again and it worked, but it's really painfull now to repair more than 30 devices :(
thanks a lot for you help and workaround!
