### ISSUE TITLE
Add support for HACS

### ISSUE THREAD

**Issue by Sjeff** [rgruebel/ha_zigbee2mqtt_networkmap#11]
If its possible can you add support for [HACS](https://github.com/custom-components/hacs)?

**Comment by smoldersonline** [comment]
+1 for HACS support.

**Comment by h4nc** [comment]
+1

**Comment by sebiweise** [comment]
Working on it. Looking for a solution to copy the www folder.

**Comment by rgruebel** [comment]
Thanks to @sebiweise (#13).

**Comment by h4nc** [comment]
Great, so is it available in hacs right now, do we have to add a repo or wait for an update of hacs?
