### ISSUE TITLE
Friendly name is not displayed on the chart

### ISSUE THREAD

**Issue by dmak** [rgruebel/ha_zigbee2mqtt_networkmap#14]
Currently the addon renders only device ID in the rectangle. It would be nice it also displays `friendly_name` (or `name` if not defined) next to device ID e.g. "Bedroom lamp (0x000157ffefb1c41a)". If none of above is defined than I suggest to render the information like it is now.

**Comment by rgruebel** [comment]
Hello dmak,
the Graphviz string is generated by Zigbee2mqtt, this component only displays it. Can you create an issue in the zigbee2mqtt project?

**Comment by dmak** [comment]
Then displaying HASS `friendly_name` is not possible...
