### ISSUE TITLE
viz.js not installed (installation using HACS)

### ISSUE THREAD

**Issue by MarsWarrior** [rgruebel/ha_zigbee2mqtt_networkmap#17]
I'm using HACS to install the component.

For some reason viz.js is NOT installed on the viz.js folder.
![image](https://user-images.githubusercontent.com/1220775/61578764-e4951700-aafb-11e9-881e-44dab68964e4.png)

**Comment by rgruebel** [comment]
That's strange. Where does the file "full.render.js.gz" come from? It's not in my repository at all. I will set up HACS in my environment  soon and test if everything works.

**Comment by rgruebel** [comment]
@MarsWarrior is the viz.js file missing in BOTH folders custom_components\zigbee2mqtt_networkmap\www\viz.js and www\community\zigbee2mqtt_networkmap\viz.js?

**Comment by MarsWarrior** [comment]
Yes, I had to wget them in both folders!

**Comment by MarsWarrior** [comment]
And this is the commit HACS is using:
![image](https://user-images.githubusercontent.com/1220775/61590481-68add400-abba-11e9-8bae-e25f6df049c4.png)

**Comment by rgruebel** [comment]
yes good idea. That would be a bug in hacs.

**Comment by rgruebel** [comment]
I've opened an issue:
custom-components/hacs#321

**Comment by MarsWarrior** [comment]
Great!

**Comment by talondnb** [comment]
I've just noticed this also affects panzoom.min.js. I had to copy the file manually to the folder before pan/zoom worked.

**Comment by rgruebel** [comment]
Hacs 0.13.0 released
