### ISSUE TITLE
HACS install status problem

### ISSUE THREAD

**Issue by sebiweise** [rgruebel/ha_zigbee2mqtt_networkmap#18]
The integration is carried out, but not noted in HACS, if necessary Issue in HACS Repo. The files will all be installed as intended.

**Comment by h4nc** [comment]
I also have this and additionally I get `404: Not Found` in my Map. Worked before installing it with hacs.
I did delete the browser cache.

**Comment by rgruebel** [comment]
But you'll still have the problem from #17. 
Maybe the problem with the installation status also depends on #17, because the installation process is not completed successfully.

**Comment by h4nc** [comment]
Yes you are right, the map doesn't show up.

And it looks like I have this issue now too: #4 

Because I get the Error: Received message for unregistered webhook ...

I did not have this issue before.

**Comment by mafede** [comment]
In principle I can update, but when I ask you to take out the map it doesn't come out.

This is my configuration:
in configuration.yaml

webhook:
zigbee2mqtt_networkmap:

in panel-iframe.yaml
networkmap:
      title: 'Zigbee Map'
      url: '/local/community/zigbee2mqtt_networkmap/map.html'
      icon: 'mdi: graphql'
#finish

This is the file structure.

![image](https://user-images.githubusercontent.com/11274463/61747338-ef6ed680-ad9d-11e9-819f-94f539462973.png)



when clicking on the icon, the update date appears but not the map.

**Comment by h4nc** [comment]
See the post above from @rgruebel 

There is some issue with installation process of hacs.

Download the files of the folder viz.js manually from gut and put them in your folder. Restart ha.

**Comment by mafede** [comment]
Perfect.

Running again.

Thank you

**Comment by dlashua** [comment]
HACS has an issue with the viz.js/viz.js file. It's never copied over.
https://github.com/custom-components/hacs/issues/321

**Comment by mafede** [comment]
@dlashua 

Perfect.

Running again.

Thank you

**Comment by dlashua** [comment]
@mafede Yes, I saw that. Glad you got it working. I was hoping the extra information provided would help the developer of this component to arrange the files in a way that would work with HACS or to work with the developer of HACS on custom-components/hacs#321 to get HACS to recognize the file correctly.

**Comment by P-Verbrugge** [comment]
So does the component not show up in HACS for you guys as well? I can install it partly, and have to fix it like described above. But the component does not show up in Hacs at all. So, I will not be able to see if it has updates.

**Comment by BeardedTinker** [comment]
Yeah, same here, missing it from list of installed components and always gives option to install.

**Comment by rgruebel** [comment]
Hacs 0.13.0 released
