### ISSUE TITLE
Routers Offline

### ISSUE THREAD

**Issue by wes1993** [rgruebel/ha_zigbee2mqtt_networkmap#19]
Hello, i have installed the last version of ZigBee2MQTT in Hass.io.
I don't know why but Routers like Philips Hue Stay offline in the map.
The coordinator (CC2531 FW 3.0) stay online.
Thanks a Lot
Stefano

**Comment by rgruebel** [comment]
Hello Stefano
the Graphviz string is generated by Zigbee2mqtt, this component only displays it. Can you create an issue in the zigbee2mqtt project?
