### ISSUE TITLE
ReferenceError: graph is not defined

### ISSUE THREAD

**Issue by papaiatis** [rgruebel/ha_zigbee2mqtt_networkmap#23]
Hi,

I followed the installation steps mentioned in readme. The new menu item appears on the left "Zigbee Map" but when I open it I get a blank screen only with the following errors in JS console:

```
GET http://192.168.2.102:8123/local/community/zigbee2mqtt_networkmap/source.js?v=1571731390327 net::ERR_ABORTED 404 (Not Found)
(anonymous) @ map.html:36
map.html:55 Uncaught ReferenceError: last_update is not defined
    at map.html:55
(anonymous) @ map.html:55
map.html:77 Uncaught ReferenceError: graph is not defined
    at updateMap (map.html:77)
    at map.html:105
```
Any idea how to resolve it? Thanks!

**Comment by papaiatis** [comment]
Looks like there is a python error when the graphiv message is received:
`TypeError: message_received() takes 1 positional argument but 3 were given`

**Comment by rgruebel** [comment]
It seems that you are using an old version of Homeassistant. The method signature of message_received changed a while ago.

**Comment by papaiatis** [comment]
So what's the recommended minimal version of HA?

**Comment by rgruebel** [comment]
i guess everything above HA 0.92 should work.

**Comment by papaiatis** [comment]
Thanks. That worked!
