### ISSUE TITLE
Device Names aren't updated

### ISSUE THREAD

**Issue by Havoc85** [rgruebel/ha_zigbee2mqtt_networkmap#26]
I update my Device Names and hoped, that they will be in the Network Map, too. But it doesn't seem to work:

![image](https://user-images.githubusercontent.com/2799774/72969231-5a3cb100-3dc5-11ea-9c69-b8aea61880dc.png)

After the renaming, there were a couple of updates of the Map, but it still stays without the new name.

![image](https://user-images.githubusercontent.com/2799774/72969059-0fbb3480-3dc5-11ea-9d74-db37495ce767.png)

Just to show where I renamed them:

![image](https://user-images.githubusercontent.com/2799774/72969430-bd2e4800-3dc5-11ea-947d-0d2b448e1891.png)

Is there anyway how I can get the names in the Networkmap, too?

**Comment by rgruebel** [comment]
The networkmap is completely generated in zigbee2mqtt and is independent from homeassistant.
But you can also set a friendly name for your devices in zigbee2mqtt
