### ISSUE TITLE
can't load it after hacs update

### ISSUE THREAD

**Issue by sagitt** [rgruebel/ha_zigbee2mqtt_networkmap#28]
after an hacs update during hass restart i see that this plugin cannot loaded

already tried to reinstall it and hacs.

**Comment by sagitt** [comment]
![Schermata 2020-03-01 alle 21 47 46](https://user-images.githubusercontent.com/169086/75633584-598a0c80-5c06-11ea-8900-61a6cd909f96.png)

**Comment by sagitt** [comment]
Sorry the problem is in mosquitto server

**Comment by sesonet** [comment]
How do you solve this issue in the mosquitto server? I have empty Zigbee Map too :(

**Comment by sagitt** [comment]
Mosquitto was stopped
