### ISSUE TITLE
Broken after zigbee2mqtt added plantuml networkmap option

### ISSUE THREAD

**Issue by regystro** [rgruebel/ha_zigbee2mqtt_networkmap#30]
I updated zigbee2mqtt to 1.14.1.
As seen in changelog, support for plantuml based network graph was added: https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.14.1

Since then, no map is displayed and Chrome console throws:

```
Uncaught (in promise) Error: syntax error in line 1 near 'plantuml'

    at render (full.render.js:50)
    at viz.js:123
    at new Promise (<anonymous>)
    at ModuleWrapper.render (viz.js:121)
    at Viz.renderString (viz.js:284)
    at Viz.renderSVGElement (viz.js:291)
    at updateMap (map.html:79)
    at map.html:213
render @ full.render.js:50
(anonymous) @ viz.js:123
ModuleWrapper.render @ viz.js:121
renderString @ viz.js:284
renderSVGElement @ viz.js:291
updateMap @ map.html:79
(anonymous) @ map.html:213
Promise.then (async)
updateMap @ map.html:80
(anonymous) @ map.html:213
```

Thank you.

**Comment by Dbroek** [comment]
I have the same issue. If there is testing to be done i can contribute.

**Comment by rgruebel** [comment]
Unfortunately I cannot reproduce the issue and I explicitly use graphviz as payload in the mqtt message.

**Comment by regystro** [comment]
I managed to get rid of the error by updating to commit 7a8eb0b and clearing browser cache.

After that I've been able to use the "Update and check" link at the bottom of the map. Until then only call to service zigbee2mqtt_networkmap.update was working for me (didn't bother me).

Now everything works flawlessly. Thank you.
