### ISSUE TITLE
Show device images?

### ISSUE THREAD

**Issue by nununo** [rgruebel/ha_zigbee2mqtt_networkmap#6]
Hi,

Thank you for this great custom component.

Would it be possible to add an image of the device based on its model reference? Something like what can be seen here: https://github.com/Koenkk/zigbee2mqtt/issues/252

Thanks in advance,
Nuno

**Comment by rgruebel** [comment]
This component displays only the graph generated by zigbee2Mqtt. I think the right way would be to add the images there  (additional payload for the topic zigbee2mqtt/bridge/networkmap)
