### ISSUE TITLE
Cant generate/update the map

### ISSUE THREAD

**Issue by YamiFrankc** [rgruebel/ha_zigbee2mqtt_networkmap#9]
Hello, 

I am trying to use this component, but it doesnt work. It doesnt update/generate the map with either the service call or the "Update Now" button.
I do not know where to look for logs for this, there is nothing about it in the hassio logs.

What can i do?
Thanks

**Comment by rgruebel** [comment]
Can you please try again with the current version? There was a problem with HA 0.92, but now it should work again.

**Comment by YamiFrankc** [comment]
Hello
I updated both HA and this component but its not working yet

**Comment by rgruebel** [comment]
You need to look in the homeassistan log, not the hassio log.

**Comment by boojew** [comment]
I'm running 0.92.1 and I get 

```
2019-04-29 23:30:15 ERROR (MainThread) [homeassistant.core] Error doing job: SSL handshake failed
Traceback (most recent call last):
  File "uvloop/sslproto.pyx", line 500, in uvloop.loop.SSLProtocol._on_handshake_complete
  File "uvloop/sslproto.pyx", line 484, in uvloop.loop.SSLProtocol._do_handshake
  File "/usr/local/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1056)
```

This was running well on 0.90 (and probably 0.91 based on last updated date)

**Comment by rgruebel** [comment]
@boojew I don't think that this error has anything to do with this component.

**Comment by boojew** [comment]
Possible - but occurs systematically when I hit update..

**Comment by YamiFrankc** [comment]
`2019-05-03 20:57:03 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for zigbee2mqtt_networkmap which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant. 2019-05-03 20:57:04 WARNING (MainThread) [homeassistant.components.http] Configuring api_password via the http component has been deprecated. Use the legacy api password auth provider instead. For instructions, see https://www.home-assistant.io/docs/authentication/providers/#legacy-api-password`

Here is the log, doesnt really say much.
I updated everything recently but still not working

**Comment by YamiFrankc** [comment]
I think I might have found out why its not working.
I changed the mqtt topic that my zigbee2mqtt uses, and reading thru the network map files it seems like it uses the default ones.
All I should need to do is change "DEFAULT_TOPIC" in __init__.py and zigbee2mqtt_networkmap.py.
And now it works.
I think adding this info to the readme.md would be useful just in case other people also changed their mqtt topic and cant figure it out :)

**Comment by rgruebel** [comment]
It is also possible to overwrite the topic via configuration.yaml. But you're right, I should add this in the README
